version: "3.8"
services:
  web:
    image: "node:alpine"
    environment:
        SHEETS_SERVER_CONFIG: /srv/persistent/config.json
    ports:
      - "0.0.0.0:80:8080"
    volumes:
      - "../persistent:/srv/persistent"
      - "../:/srv/src"
    entrypoint: /srv/src/docker/entrypoint.sh